#!/bin/bash
CAPACITY=$(cat /sys/class/power_supply/CMB1/capacity)
CURRENT=$(cat /sys/class/power_supply/CMB1/status)
case "$CURRENT" in 
	"Charging") printf "\xef\x83\xa7 %d%%" $CAPACITY;;
        "Discharging")
		if [[ "$CAPACITY" -gt 75 ]]; then 
			printf "\xef\x89\x80 %d%%" $CAPACITY
		elif [[ "$CAPACITY" -gt 50 ]]; then
			printf "\xef\x89\x81 %d%%" $CAPACITY
		elif [[ "$CAPACITY" -gt 25 ]]; then
			printf "\xef\x89\x82 %d%%" $CAPACITY
		elif [[ "$CAPACITY" -gt 0 ]]; then  
			printf "\xef\x89\x83 %d%%" $CAPACITY
		fi;;
esac
