#!/bin/bash
CAPACITY=$(cat /sys/class/power_supply/CMB1/capacity)
CURRENT=$(cat /sys/class/power_supply/CMB1/status)
case "$CURRENT" in 
	"Charging") echo "󰂄 $CAPACITY%";;
        "Discharging")
		case "$CAPACITY" in 
			100|9[0-9]|8[0-9]) echo "  $CAPACITY%";;
			7[0-9]|6[0-9])     echo "  $CAPACITY%";;
			5[0-9]|4[0-9])     echo "  $CAPACITY%";;
			3[0-9]|2[0-9])     echo "  $CAPACITY%";;
			*)		   echo "  $CAPACITY%";;
		esac
esac
