#!/bin/bash
ARRAY=()
vol=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
split=$(echo $vol | tr " " "\n")
for mots in $split; do
	ARRAY+=($mots)
done
op=$(echo "${ARRAY[1]} * 100" | bc)
a=$(printf "%.0f\n" "$op")
printf "\xef\x80\xa8 %2d%%" "$a"
